trigger:
- main


stages:
  - stage: python
    displayName: python setup
    jobs:
      - job: python
        displayName: download and create env for python 
        pool: 
          vmImage: 'windows-latest'
        steps: 
        - task: AzureCLI@2
          inputs:
            azureSubscription: "testscfornewrepo"
            scriptType: 'bash'
            scriptLocation: inlineScript
            inlineScript: |
              git clone -b master https://github.com/Thiru799/raviLogin.git temp_project
              ls
              mkdir -p /d/Projects/demo 
              cp -r temp_project/* /d/Projects/demo
              ls /d/Projects/demo/

              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'bot-connection'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    python3 -m venv enve
                    ls
                    echo "Activating virtual environment..."
                    source enve/Scripts/activate
                    curl https://pypi.org/simpl
                    pip install --prefer-binary -r requirements.txt && echo "Installation successful!"
                    export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080





            
