trigger:
- main


stages:
  - stage: python
    displayName: python setup
    jobs:
      - job: python
        displayName: download and create env for python 
        pool: ubuntu-latest
        steps: 
        - checkout: self
        - task: AzureCLI@2
          inputs:
            azureSubscription: "azure service connection name"
            scriptType: 'bash'
            scriptLocation: inlineScript
            inlineScript: |
              pip install -r requirements.txt